#!/usr/bin/env bash
#set -exou pipefail
set -x

pip3 install -r requirements.txt

sudo mkdir -p /usr/"$USER"
sudo cp py /usr/"$USER"
sudo chmod +x /usr/"$USER"/py
echo "export PATH=\"/usr/\$USER:\$PATH\"" >> ~/.bashrc
source ~/.bashrc
