#!/usr/bin/env bash
#set -exou pipefail
set -x
# python3 is installed by default in Ubuntu 20.04 LTS
pip3 install mypy
pip3 install black
pip3 install isort

sudo mkdir -p /usr/"$USER"
sudo cp py /usr/"$USER"
sudo chmod +x /usr/"$USER"/py
grep -q 'export PATH=\"/usr/\$USER:\$PATH\"' ~/.bashrc # 0 is found, 1 is not found
grep_return=$?
if [[ $grep_return == 1 ]]; then
    echo "export PATH=\"/usr/\$USER:\$PATH\"" >> ~/.bashrc
fi
source ~/.bashrc
